[package]
name = "ghostsync"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.4"
xattr = "1.1"
chrono = "0.4"
clap = { version = "4.4", features = ["derive"] }
libc = "0.2"
termcolor = "1.4.1"
